branches:
  only:
    - master
language: python
python:
- '3.4'
- '3.5'
before_script:
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && pip install pygithub; exit 0; fi
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && pip install pygithub3; exit 0; fi
script:
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && python3 tools/deploy.py; exit 0; fi
- python3 tools/sqf_validator.py
env:
  global:
  - secure: "OF5qAqtQpZ9+G1b5DxePLzmLeASImGuU1GYTXD4tnc6NSb+SLLBLVT7MF9nMlMpqwrD//QLPGhGAOlmTtrXAa79R5RJazJ/lzVSdQEZ4ETmCl31S/lXLBYZ25HvmaIkXKm/3SMHs/tWSCqpjeDQY1trV7wkuE5VDGDJaDwm+LX11efYC/LJKvFzbNCAp7VA0ICg251tQz5czF7HVYfn2W44p5DKoT9PrgbbLqIWt2Ji6YarTa74YH1dJ/7C3VzYWA5CQdWYaLFlawQMrTGaRHkARDtmAQmStKGZdELnln0RXpaZqqSK/1TYndfmZIjQqaNWUWlCvzUtrM6wD3zOYWwmZmUdiOy7JS/y5f/ufu80xnCHx7Ho9+10j9OtC869qOFRx3HbF1Wiv0dd8/Le37l8uDy/5+N0jowK8fnAgbrcpqzk0pehDl7s9aUb0lSquQRwSiYWCrspN7TZWZ55yq915O2KJ9rx5drAZLsb7Nt7l14DRQE7LIt/PBNUYQ2Y4V+57ECQTJ5rqJc5yFkQ1AInbFaChUrjbXGWXPOj0tp+YMRJF+iSiKwJC+qepNhkvMtkmnfevbAEzdryH2I7tuc6B9FlfL+Xfb8xv8fsQb/4S/XBs/q9wE//dzWEN25hli8vuBKWVQZIH18QoXA+4/XITJnd8LIC5UJMcbBRIM+4="
notifications:
  email:
    on_success: never
    on_failure: change
