name = "TAC Mods"
prefix = "tac"
author = "TAC Mod Team"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_tac_ca.paa",
    "logo_tac_small_ca.paa"
]

modname = "{{prefix}}_mods"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

prebuild = ["!compile_sqf"]
postbuild = ["!compile_sqf_cleanup"]
releasebuild = [
    "@zip {{prefix}}_mods_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# SQF Compilation
[scripts.compile_sqf]
steps_windows = [
    "echo Compile SQF",
    "python tools/compile_sqf.py cleanup build"
]
only_release = true
show_output = true

[scripts.compile_sqf_cleanup]
steps_windows = [
    "echo Compile SQF Cleanup",
    "python tools/compile_sqf.py cleanup"
]
only_release = true
show_output = true

[scripts.extensions]
show_output = true
steps_windows = [
    "cd extensions\\vcproj && cmake .. -A Win32 && msbuild TAC.sln /m /p:Configuration=RelWithDebInfo",
    "cd extensions\\vcproj64 && cmake .. -A x64 && msbuild TAC.sln /m /p:Configuration=RelWithDebInfo"
]
steps_linux = [
    "cd extensions/build && cmake .. && make",
    "cd extensions/build && CXX=$(eval $(which g++-w64-mingw-i686)) cmake .. && make",
    "find ./extensions/build/ ( -name \"*.so\" -o -name \"*.dll\" ) -exec cp {} ./"
]
